name: Deploy All

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages and install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixos-rocksmith
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true

      - name: Build all packages
        run: |
          set -eo pipefail
          for p in $(nix eval --json .#packages.x86_64-linux | jq -r 'keys[]'); do
            nix build --no-link --print-out-paths ".#${p}" || exit $?
          done
        env:
          NIX_REMOTE: "daemon"
